version: 2
updates:
  - package-ecosystem: gomod
    directory: /reference/go
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /conformance
    schedule:
      interval: monthly
